# Copyright (c) 2026 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation

# Generated by Claude Opus 4.6

# Stage 1: Build — download Claude Code, install gritty, collect minimal rootfs
FROM node:22-slim AS builder

ARG CLAUDE_CODE_VERSION=2.1.81
ARG TARGETARCH

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      curl ca-certificates python3 make g++ procps jq && \
    rm -rf /var/lib/apt/lists/*

# Download Claude Code native binary
RUN set -e && \
    case "${TARGETARCH}" in \
      amd64) PLATFORM="linux-x64" ;; \
      arm64) PLATFORM="linux-arm64" ;; \
      *) echo "Unsupported architecture: ${TARGETARCH}" && exit 1 ;; \
    esac && \
    curl -fsSL -o /usr/local/bin/claude \
      "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/${CLAUDE_CODE_VERSION}/${PLATFORM}/claude" && \
    chmod +x /usr/local/bin/claude

# Install gritty globally and prune unnecessary files
RUN npm install -g gritty && \
    npm cache clean --force && \
    find /usr/local/lib/node_modules/gritty -type f \( \
      -name "*.md" -o -name "*.txt" -o -name "*.map" \
      -o -name "LICENSE*" -o -name "CHANGELOG*" -o -name "HISTORY*" \
      -o -name "Makefile" -o -name "*.yml" -o -name "*.yaml" \
    \) -delete 2>/dev/null; true

# Collect minimal rootfs — only binaries + shared libs needed at runtime
COPY collect-rootfs.sh /tmp/collect-rootfs.sh
RUN chmod +x /tmp/collect-rootfs.sh && bash /tmp/collect-rootfs.sh

# Stage 2: Minimal image from scratch
FROM scratch

COPY --from=builder /rootfs/ /

# Claude Code config files
COPY CLAUDE.md /opt/claude-skills/CLAUDE.md
COPY settings.json /opt/claude-skills/settings.json
COPY claude.json /opt/claude-skills/claude.json

ENV PATH="/usr/local/bin:/usr/bin:/bin" \
    HOME="/root" \
    LANG="C.UTF-8" \
    CLAUDE_CODE_SKIP_PERMISSIONS_CONFIRMATION="1"

EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

LABEL org.opencontainers.image.description="Dashboard Agent: Claude Code with gritty terminal for Eclipse Che" \
      org.opencontainers.image.source="https://github.com/olexii4/che-ai-tool-images"
