# Copyright (c) 2026 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation

# Generated by Claude Opus 4.6

# Stage 1: Download Claude Code native binary + install gritty
FROM node:22-slim AS builder

ARG CLAUDE_CODE_VERSION=2.1.81
ARG TARGETARCH

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl ca-certificates python3 make g++ && \
    rm -rf /var/lib/apt/lists/*

# Download Claude Code native binary
RUN set -e && \
    case "${TARGETARCH}" in \
      amd64) PLATFORM="linux-x64" ;; \
      arm64) PLATFORM="linux-arm64" ;; \
      *) echo "Unsupported architecture: ${TARGETARCH}" && exit 1 ;; \
    esac && \
    curl -fsSL -o /usr/local/bin/claude \
      "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/${CLAUDE_CODE_VERSION}/${PLATFORM}/claude" && \
    chmod +x /usr/local/bin/claude

# Install gritty globally (xterm.js + node-pty + socket.io terminal)
RUN npm install -g gritty && \
    npm cache clean --force

# Stage 2: Minimal runtime image
FROM registry.access.redhat.com/ubi10/ubi-minimal:10.0

# Install bash, Node.js for gritty, and jq/python3 for Claude Code tools
RUN microdnf install -y bash procps-ng nodejs jq python3 && \
    microdnf clean all

# Copy Claude Code native binary
COPY --from=builder /usr/local/bin/claude /usr/local/bin/claude-bin

# Copy gritty from builder (global node_modules)
COPY --from=builder /usr/local/lib/node_modules /usr/local/lib/node_modules

# Symlink gritty binary
RUN ln -s /usr/local/lib/node_modules/gritty/bin/gritty.js /usr/local/bin/gritty

# Wrapper script that redirects HOME to a writable location
# for OpenShift arbitrary UIDs where $HOME is not writable.
RUN printf '#!/bin/sh\n\
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"\n\
CLAUDE_TMP_HOME="/tmp/claude-home"\n\
if [ ! -w "$HOME" ]; then\n\
  export HOME="$CLAUDE_TMP_HOME"\n\
fi\n\
mkdir -p "$HOME/.claude/sessions" "$HOME/.claude/plugins" "$HOME/.local/bin"\n\
export PATH="$HOME/.local/bin:$SCRIPT_DIR:$PATH"\n\
# Copy skills CLAUDE.md into working directory if not present\n\
if [ ! -f "$HOME/CLAUDE.md" ]; then\n\
  cp /opt/claude-skills/CLAUDE.md "$HOME/CLAUDE.md" 2>/dev/null || true\n\
fi\n\
# Copy Claude Code settings if not present\n\
if [ ! -f "$HOME/.claude/settings.json" ]; then\n\
  cp /opt/claude-skills/settings.json "$HOME/.claude/settings.json" 2>/dev/null || true\n\
fi\n\
# Copy onboarding state to skip first-run wizard\n\
if [ ! -f "$HOME/.claude.json" ]; then\n\
  cp /opt/claude-skills/claude.json "$HOME/.claude.json" 2>/dev/null || true\n\
fi\n\
exec "$SCRIPT_DIR/claude-bin" "$@"\n' > /usr/local/bin/claude && \
    chmod +x /usr/local/bin/claude

# Claude Code skills for devfile authoring
COPY CLAUDE.md /opt/claude-skills/CLAUDE.md

# Claude Code settings (model, environment)
COPY settings.json /opt/claude-skills/settings.json

# Claude Code onboarding state (skips first-run wizard)
COPY claude.json /opt/claude-skills/claude.json

# Create .bashrc with env vars for Claude Code
RUN printf '# Claude Code agent shell\nexport CLAUDE_CODE_SKIP_PERMISSIONS_CONFIRMATION=1\n' > /opt/claude-skills/.bashrc

# Entrypoint script: sets up HOME and starts gritty
RUN printf '#!/bin/sh\n\
CLAUDE_TMP_HOME="/tmp/claude-home"\n\
if [ ! -w "$HOME" ]; then\n\
  export HOME="$CLAUDE_TMP_HOME"\n\
fi\n\
mkdir -p "$HOME/.claude/sessions" "$HOME/.claude/plugins" "$HOME/.local/bin"\n\
export PATH="$HOME/.local/bin:/usr/local/bin:$PATH"\n\
export CLAUDE_CODE_SKIP_PERMISSIONS_CONFIRMATION=1\n\
# Copy .bashrc\n\
cp /opt/claude-skills/.bashrc "$HOME/.bashrc" 2>/dev/null || true\n\
# Copy skills CLAUDE.md\n\
if [ ! -f "$HOME/CLAUDE.md" ]; then\n\
  cp /opt/claude-skills/CLAUDE.md "$HOME/CLAUDE.md" 2>/dev/null || true\n\
fi\n\
# Copy Claude Code settings\n\
if [ ! -f "$HOME/.claude/settings.json" ]; then\n\
  cp /opt/claude-skills/settings.json "$HOME/.claude/settings.json" 2>/dev/null || true\n\
fi\n\
# Copy onboarding state to skip first-run wizard\n\
if [ ! -f "$HOME/.claude.json" ]; then\n\
  cp /opt/claude-skills/claude.json "$HOME/.claude.json" 2>/dev/null || true\n\
fi\n\
exec node /usr/local/lib/node_modules/gritty/bin/gritty.js --port 8080 --command bash\n' > /usr/local/bin/entrypoint.sh && \
    chmod +x /usr/local/bin/entrypoint.sh

# Gritty port
EXPOSE 8080

CMD ["/usr/local/bin/entrypoint.sh"]

LABEL org.opencontainers.image.description="Dashboard Agent: Claude Code with gritty terminal for Eclipse Che" \
      org.opencontainers.image.source="https://github.com/olexii4/che-ai-tool-images"
