/*
 * Copyright (c) 2026 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

// Wetty-inspired WebSocket terminal server.
// Spawns a PTY shell and bridges it to WebSocket clients with output batching
// and flow control for smooth rendering.
//
// Protocol:
//   client -> server: raw text (terminal input) or JSON { type: "resize", cols, rows }
//   server -> client: raw text (batched PTY output)

const fs = require('fs');
const http = require('http');
const { WebSocketServer } = require('ws');
const pty = require('node-pty');

const PORT = parseInt(process.env.TERMINAL_PORT || '8080', 10);
const SHELL = process.env.SHELL || '/bin/bash';

// Output batching: coalesce small PTY reads into larger chunks.
// Wetty uses a 2ms flush interval; we use the same.
const BATCH_INTERVAL_MS = 2;
const BATCH_MAX_BYTES = 512 * 1024; // 512 KB max before forced flush

// Flow control: pause PTY when unacked data exceeds high watermark.
const FLOW_HIGH = 2 * 1024 * 1024; // 2 MB
const FLOW_LOW = 512 * 1024; // 512 KB

// Ensure HOME is writable (OpenShift arbitrary UIDs)
if (!isWritable(process.env.HOME)) {
  process.env.HOME = '/tmp/claude-home';
}
mkdirp(process.env.HOME);
mkdirp(process.env.HOME + '/.claude');
const skillsSrc = '/opt/claude-skills/CLAUDE.md';
const skillsDst = process.env.HOME + '/CLAUDE.md';
if (fs.existsSync(skillsSrc) && !fs.existsSync(skillsDst)) {
  fs.copyFileSync(skillsSrc, skillsDst);
}

// Health check endpoint
const server = http.createServer((req, res) => {
  if (req.url === '/healthz') {
    res.writeHead(200, { 'Content-Type': 'text/plain' });
    res.end('ok');
    return;
  }
  res.writeHead(404);
  res.end();
});

const wss = new WebSocketServer({
  server,
  path: '/terminal',
  perMessageDeflate: false, // disable compression for lower latency
});

wss.on('connection', (ws) => {
  console.log('[terminal-server] Client connected');

  const ptyProcess = pty.spawn(SHELL, [], {
    name: 'xterm-256color',
    cols: 80,
    rows: 24,
    cwd: process.env.HOME,
    env: Object.assign({}, process.env, {
      TERM: 'xterm-256color',
      COLORTERM: 'truecolor',
      LANG: process.env.LANG || 'en_US.UTF-8',
      PATH: '/opt/claude-code/bin:' + process.env.PATH,
    }),
  });

  // --- Output batching (wetty tinybuffer pattern) ---
  let outputBuffer = '';
  let flushTimer = null;
  let unackedBytes = 0;
  let isPaused = false;

  function flushOutput() {
    flushTimer = null;
    if (outputBuffer.length === 0) return;
    const chunk = outputBuffer;
    outputBuffer = '';
    try {
      if (ws.readyState === 1) { // WebSocket.OPEN
        ws.send(chunk);
        unackedBytes += chunk.length;
        // Flow control: pause PTY if too much unacked data
        if (!isPaused && unackedBytes > FLOW_HIGH) {
          ptyProcess.pause();
          isPaused = true;
        }
      }
    } catch (e) {
      // Client disconnected
    }
  }

  function bufferOutput(data) {
    outputBuffer += data;
    if (outputBuffer.length >= BATCH_MAX_BYTES) {
      // Forced flush if buffer is too large
      if (flushTimer) {
        clearTimeout(flushTimer);
      }
      flushOutput();
    } else if (!flushTimer) {
      flushTimer = setTimeout(flushOutput, BATCH_INTERVAL_MS);
    }
  }

  // PTY stdout -> buffered WebSocket
  ptyProcess.onData((data) => {
    bufferOutput(data);
  });

  ptyProcess.onExit(({ exitCode }) => {
    console.log(`[terminal-server] PTY exited with code ${exitCode}`);
    // Flush remaining output
    if (flushTimer) {
      clearTimeout(flushTimer);
    }
    flushOutput();
    ws.close();
  });

  // WebSocket -> PTY stdin
  ws.on('message', (msg) => {
    const data = msg.toString();
    try {
      const parsed = JSON.parse(data);
      if (parsed.type === 'resize' && parsed.cols && parsed.rows) {
        ptyProcess.resize(
          Math.max(1, Math.min(parsed.cols, 500)),
          Math.max(1, Math.min(parsed.rows, 200))
        );
        return;
      }
      // Flow control: client acknowledges received bytes
      if (parsed.type === 'ack' && typeof parsed.bytes === 'number') {
        unackedBytes = Math.max(0, unackedBytes - parsed.bytes);
        if (isPaused && unackedBytes < FLOW_LOW) {
          ptyProcess.resume();
          isPaused = false;
        }
        return;
      }
    } catch (e) {
      // Not JSON, treat as terminal input
    }
    ptyProcess.write(data);
  });

  ws.on('close', () => {
    console.log('[terminal-server] Client disconnected');
    if (flushTimer) {
      clearTimeout(flushTimer);
    }
    ptyProcess.kill();
  });

  // Ping/pong keepalive (wetty uses 54s)
  const pingInterval = setInterval(() => {
    if (ws.readyState === 1) {
      ws.ping();
    }
  }, 30000);

  ws.on('close', () => clearInterval(pingInterval));
  ws.on('error', () => clearInterval(pingInterval));
});

server.listen(PORT, '0.0.0.0', () => {
  console.log(`[terminal-server] Listening on port ${PORT}`);
});

function isWritable(dir) {
  try {
    fs.accessSync(dir, fs.constants.W_OK);
    return true;
  } catch (e) {
    return false;
  }
}

function mkdirp(dir) {
  fs.mkdirSync(dir, { recursive: true });
}
